nohup: ignoring input
2025-03-23 17:48:20,748 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-pressure-levels
Traceback (most recent call last):
  File "/local1/storage1/jml559/miniconda3/envs/climdyn/lib/python3.7/site-packages/cdsapi/api.py", line 459, in _api
    result.raise_for_status()
  File "/local1/storage1/jml559/miniconda3/envs/climdyn/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-pressure-levels

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_era5_plevels.py", line 161, in <module>
    client.retrieve(dataset, request).download()
  File "/local1/storage1/jml559/miniconda3/envs/climdyn/lib/python3.7/site-packages/cdsapi/api.py", line 381, in retrieve
    result = self._api("%s/resources/%s" % (self.url, name), request, "POST")
  File "/local1/storage1/jml559/miniconda3/envs/climdyn/lib/python3.7/site-packages/cdsapi/api.py", line 481, in _api
    raise Exception(error)
Exception: Not Found
